### ISSUE TITLE
Issue with model generating inconsistent num of questions

### ISSUE THREAD

**Issue by spentuker** [spentuker/projectseekhan#2]
Even when I tell the prompt to generate 30 questions, it sometimes doesnt, like 2/10 times. I made the model generate "30" questions with the help of prompt engineering. But Idk if that is the right way to do it. I will figure smthn out.

**Comment by vipulchinmay** [comment]
### **Issue Resolved**
This issue of the model generating inconsistent number of questions was resolved by changing the number of tokens during the finetuning of the model.
