### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by Srujana1008** [spentuker/projectseekhan#8]
When we click on Generate questions , it generates questions but sometimes it displays "model requires more  system memory than available. "
![Screenshot 2024-12-12 213713](https://github.com/user-attachments/assets/3191dfe0-7739-40e1-a4a8-a76e84f09268)

**Comment by vipulchinmay** [comment]
it got solved by upgrading to a much efficient machine with an integrated GPU, and by downloading the classifier model locally into the machine.

![WhatsApp Image 2024-12-25 at 23 28 32_1b5e425e](https://github.com/user-attachments/assets/d9bd4581-fd2e-4397-8753-357aede35162)
